import { HomeClient } from "@/components/home/HomeClient";
import type { Listing, Agency, ListingImage } from "@/lib/types";

// Mock data for demo - will be replaced with real data from database
const MOCK_LISTINGS: Array<Listing & { agency?: Agency | null; images: ListingImage[] }> = [
  {
    id: "1",
    slug: "luxury-apartment-baku-center",
    title: "Lüks Mənzil Bakının Mərkəzində",
    description: "Full təmirli, mebelli 3 otaqlı mənzil",
    price: 180000,
    area: 120,
    rooms: 3,
    floor: 5,
    totalFloors: 9,
    address: "Neftçilər prospekti 25, Nəsimi rayonu",
    district: "Nəsimi",
    city: "Bakı",
    lat: 40.3777,
    lng: 49.8920,
    phone: "+994501234567",
    email: null,
    type: "SALE",
    category: "APARTMENT",
    status: "ACTIVE",
    publishedAt: new Date("2026-06-10"),
    rejectionReason: null,
    isFeatured: true,
    views: 245,
    userId: "user1",
    agencyId: "agency1",
    createdAt: new Date("2026-06-10"),
    updatedAt: new Date("2026-06-10"),
    agency: {
      id: "agency1",
      name: "Premium Əmlak",
      logo: "/agencies/premium.png",
      description: null,
      address: null,
      phone: null,
      email: null,
      isVerified: true,
      createdAt: new Date("2026-01-01"),
    },
    images: [
      { id: "img1", listingId: "1", url: "/listings/apt1.jpg", order: 0 },
    ],
  },
  {
    id: "2",
    slug: "modern-house-gusar",
    title: "Müasir Bağ Evi Qusarda",
    description: "Təbiət qoynunda rahat yaşayış",
    price: 95000,
    area: 200,
    rooms: 4,
    floor: null,
    totalFloors: null,
    address: "Heydər Əliyev küçəsi 45",
    district: null,
    city: "Qusar",
    lat: 41.4267,
    lng: 48.4297,
    phone: "+994551234567",
    email: null,
    type: "SALE",
    category: "HOUSE",
    status: "ACTIVE",
    publishedAt: new Date("2026-06-12"),
    rejectionReason: null,
    isFeatured: false,
    views: 128,
    userId: "user2",
    agencyId: null,
    createdAt: new Date("2026-06-12"),
    updatedAt: new Date("2026-06-12"),
    agency: null,
    images: [
      { id: "img2", listingId: "2", url: "/listings/house1.jpg", order: 0 },
    ],
  },
  {
    id: "3",
    slug: "commercial-office-baku",
    title: "Ofis Sahəsi Nizami metrosuna yaxın",
    description: "Kirayə üçün ofis sahəsi",
    price: 2500,
    area: 85,
    rooms: null,
    floor: 3,
    totalFloors: 7,
    address: "Nizami küçəsi 12",
    district: "Nəsimi",
    city: "Bakı",
    lat: 40.3800,
    lng: 49.8500,
    phone: "+994501112233",
    email: null,
    type: "RENT",
    category: "COMMERCIAL",
    status: "ACTIVE",
    publishedAt: new Date("2026-06-13"),
    rejectionReason: null,
    isFeatured: false,
    views: 89,
    userId: "user3",
    agencyId: "agency1",
    createdAt: new Date("2026-06-13"),
    updatedAt: new Date("2026-06-13"),
    agency: {
      id: "agency1",
      name: "Premium Əmlak",
      logo: "/agencies/premium.png",
      description: null,
      address: null,
      phone: null,
      email: null,
      isVerified: true,
      createdAt: new Date("2026-01-01"),
    },
    images: [
      { id: "img3", listingId: "3", url: "/listings/office1.jpg", order: 0 },
    ],
  },
  {
    id: "4",
    slug: "land-plot-baku-suburbs",
    title: "Torpaq Sahəsi Bakı ətrafı",
    description: "Tikinti üçün torpaq",
    price: 45000,
    area: 600,
    rooms: null,
    floor: null,
    totalFloors: null,
    address: "Mərdəkan qəsəbəsi",
    district: "Xəzər",
    city: "Bakı",
    lat: 40.4667,
    lng: 50.0833,
    phone: "+994552223344",
    email: null,
    type: "SALE",
    category: "LAND",
    status: "ACTIVE",
    publishedAt: new Date("2026-06-11"),
    rejectionReason: null,
    isFeatured: false,
    views: 67,
    userId: "user4",
    agencyId: null,
    createdAt: new Date("2026-06-11"),
    updatedAt: new Date("2026-06-11"),
    agency: null,
    images: [
      { id: "img4", listingId: "4", url: "/listings/land1.jpg", order: 0 },
    ],
  },
  {
    id: "5",
    slug: "studio-apartment-rent",
    title: "1 Otaqlı Mənzil Kirayə",
    description: "Yeni tikili, tam təmirli",
    price: 800,
    area: 45,
    rooms: 1,
    floor: 12,
    totalFloors: 16,
    address: "28 May küçəsi 89",
    district: "Nəsimi",
    city: "Bakı",
    lat: 40.3850,
    lng: 49.8600,
    phone: "+994503334455",
    email: null,
    type: "RENT",
    category: "APARTMENT",
    status: "ACTIVE",
    publishedAt: new Date("2026-06-14"),
    rejectionReason: null,
    isFeatured: false,
    views: 34,
    userId: "user5",
    agencyId: null,
    createdAt: new Date("2026-06-14"),
    updatedAt: new Date("2026-06-14"),
    agency: null,
    images: [
      { id: "img5", listingId: "5", url: "/listings/studio1.jpg", order: 0 },
    ],
  },
  {
    id: "6",
    slug: "villa-seaside-baku",
    title: "Villa Dəniz kənarında",
    description: "Hovuzlu villa",
    price: 450000,
    area: 350,
    rooms: 6,
    floor: null,
    totalFloors: null,
    address: "Şıxov dairəsi",
    district: "Qaradağ",
    city: "Bakı",
    lat: 40.3500,
    lng: 50.0000,
    phone: "+994554445566",
    email: null,
    type: "SALE",
    category: "HOUSE",
    status: "ACTIVE",
    publishedAt: new Date("2026-06-09"),
    rejectionReason: null,
    isFeatured: true,
    views: 412,
    userId: "user6",
    agencyId: "agency1",
    createdAt: new Date("2026-06-09"),
    updatedAt: new Date("2026-06-09"),
    agency: {
      id: "agency1",
      name: "Premium Əmlak",
      logo: "/agencies/premium.png",
      description: null,
      address: null,
      phone: null,
      email: null,
      isVerified: true,
      createdAt: new Date("2026-01-01"),
    },
    images: [
      { id: "img6", listingId: "6", url: "/listings/villa1.jpg", order: 0 },
    ],
  },
];

export default function HomePage() {
  return <HomeClient listings={MOCK_LISTINGS} />;
}
